language: node_js

node_js:
  - node

services:
  - mongodb
  - rabbitmq

install:
  - npm install

script:
  - npm test
  
deploy:
  provider: heroku
  app: breviloquentia-post
  api_key:
    secure: gI19iqysLmXPUvxgAgx1A8x6J07jIpDuLQ0XitP/1amt2cspaczE58v4m1T9RNlq94ogdHV+o2qHDPKMV4ilfzAM906FDVbu8DkXLFlI3FxeNABiCb3VAYzz79xu6VIJ1uSiRjBxpSW58tkmk6o8+iI+oLsUKFmJZvqRXOoAdVWDNRM0tywhm2zLqx/sO4IwaT8WzjS5bRzMOrPi7v2ZHKOSV0lfQnx+paKNR29KjyOdwn2V3wCCdoX/AjHtatu6oxDieSAGYQpz1QQqDB9b21D5qMV7SqaLnXh894+mA7SarrdsvtDj3Tnkh2zq1Q/WJ/qnIETwv8naE8JD0/ZaaQa991xNLZzhxNJWRgugfirflTbsHUyaqT/2oBEQSq754CASpjTTAA1uDQ75egoIOtAaW14dyV5yXW4yNPnjFk8UQZ63/fe/bTpEhQZHwxNkPGm9lLpAlznWuTUc69exr8sWhxdlzA6T8nA8su+aYda8rXtuAXdw70gBAGbWujxoMUlp8Pe7UAL4k8vR5a046kfFA08ZKRuMovgoYMcO/8jstKODTHrl+PCl7q5F9kegKsAiihuCz8o3VVrQPcgv8/oyZeJ03AKkwF1dQvYn98icM6TmbYD0yWX5RFx2lu3LvvGTdib/KnCBYPPd5rQZX1W7YEy2RpHr9uaa92KK3U4=
