language: node_js
node_js:
  - "node"

services: mongodb

install:
  - npm install

script:
  - npm test

deploy:
	provider: heroku
	app: breviloquentia-post
	api_key:
		secure: cQVyHDTvx3s0Oztk8CZuhkLez0pFEoxGEHBC1NSfpDCTgtOno9gjjlLG4c+NEK1m2D4RviX75O2Xs//U09ZK1d3nm/RnJ8bRS5+S/QMbWMysAqYJWVZm+SzWoUbf5p3te4ZFNHIYOrGjREugx3D3h/ozguxbiIxXHzL124Tcykrp4V0jwdzdQS9cbnzZIRXmlCVRHRfhN25Z6QZBa15coGPfTmIyGWJmGJNvSZumjmiW1JIq3UMVW2sxAwmfLw53NRgc6JoN36WUOL5lP7VOxSylNi0N9MKZ5wNm7QX1AmQN5qk6/Z4+mLY3rMSOymdCHP7jGgmhMCLz4EhkFzc+62xmRT0x/KmvrRhy9O/1NzMvu//x3Y+7X3NiBazIZ9K4aDFzFOsgmDlLTj3+AVrxC7KLxBAevGPm9HD6rZcP1tu4qX/jRrYastxt44E5cKAd730k3ixcI367dEIB2ipdp4fCeN1GI1OIsiATZnEOrp4budLoGGemK+fTbzrTsdGzjYZkpGh8ko4ATiwIKGZCG++Oa00fpiZfAKH+dp7eNz1Wb3bP/JcI9Qmjjoe0MdnExrYPIrc4ZY5A07LD3tQmq5uxU42ZeojWuomO5y/UNZcYhSry1HS1Mtrrd83bt7cCcufVxv7UcsViCaWuL/KbEa3qxIWShfCtL3rejcaRiaM=